// lib/data.ts

import { TokenCardProps } from "./types";

// New Pairs (recently launched tokens)
export const newPairsData: TokenCardProps[] = [
  {
    imageUrl: "/1.png",
    imageAlt: "Max Token",
    address: "6R7C...FK9p",
    showStatusIcon: true,
    name: "Max",
    description: "The Max Protocol",
    age: "10m",
    userCount: 183,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "1/155",
    marketCap: "$540K",
    volume: "$34K",
    fee: 0.014,
    txCount: 1095,
    badgeValues: ["14%", "0% 4d", "13%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Max Button Clicked!"),
  },
  {
    imageUrl: "/2.png",
    imageAlt: "Cutt Token",
    address: "A89G...Nvab",
    showStatusIcon: true,
    name: "Cutt",
    description: "Cutt Protocol",
    age: "9m",
    userCount: 83,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "0/1",
    marketCap: "$119K",
    volume: "$30K",
    fee: 0.04,
    txCount: 164,
    badgeValues: ["6%", "0%", "0%", "11%", "0%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Cutt Button Clicked!"),
  },
  {
    imageUrl: "/3.png",
    imageAlt: "VIBINGCAT Token",
    address: "7rfc...pump",
    showStatusIcon: true,
    name: "VIBINGCAT",
    description: "Vibing Cat Community",
    age: "4h",
    userCount: 64,
    flagCount: 4,
    trophyCount: 0,
    shieldStatus: "0/1",
    marketCap: "$60.8K",
    volume: "$16K",
    fee: 0.091,
    txCount: 123,
    badgeValues: ["19%", "0% 6d", "0%", "74%", "0%"],
    solAmount: 0,
    onSolButtonClick: () => alert("VIBINGCAT Button Clicked!"),
  },
  {
    imageUrl: "/4.png",
    imageAlt: "XPL/SOL Token",
    address: "XPL...SOL1",
    showStatusIcon: false,
    name: "XPL/SOL",
    description: "XPL Plasma Exchange",
    age: "2h",
    userCount: 156,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "5/25",
    marketCap: "$3.41M",
    volume: "$242K",
    fee: 0.025,
    txCount: 890,
    badgeValues: ["45%", "5% 2h", "15%", "2%", "8%"],
    solAmount: 0,
    onSolButtonClick: () => alert("XPL/SOL Button Clicked!"),
  },
  {
    imageUrl: "/5.png",
    imageAlt: "NOVA Token",
    address: "NOVA...x7Y2",
    showStatusIcon: true,
    name: "NOVA",
    description: "Nova Finance",
    age: "1h",
    userCount: 245,
    flagCount: 0,
    trophyCount: 1,
    shieldStatus: "8/40",
    marketCap: "$890K",
    volume: "$120K",
    fee: 0.08,
    txCount: 1250,
    badgeValues: ["35%", "8% 1h", "20%", "3%", "6%"],
    solAmount: 0,
    onSolButtonClick: () => alert("NOVA Button Clicked!"),
  },
  {
    imageUrl: "/6.png",
    imageAlt: "PULSE Token",
    address: "PULS...E9z4",
    showStatusIcon: false,
    name: "PULSE",
    description: "Pulse Network",
    age: "30m",
    userCount: 89,
    flagCount: 1,
    trophyCount: 0,
    shieldStatus: "2/100",
    marketCap: "$280K",
    volume: "$45K",
    fee: 0.15,
    txCount: 456,
    badgeValues: ["12%", "2% 30m", "8%", "5%", "3%"],
    solAmount: 0,
    onSolButtonClick: () => alert("PULSE Button Clicked!"),
  },
  {
    imageUrl: "/7.png",
    imageAlt: "ZOOM Token",
    address: "ZOOM...M3k8",
    showStatusIcon: true,
    name: "ZOOM",
    description: "Zoom Protocol",
    age: "45m",
    userCount: 134,
    flagCount: 0,
    trophyCount: 3,
    shieldStatus: "15/60",
    marketCap: "$650K",
    volume: "$85K",
    fee: 0.06,
    txCount: 780,
    badgeValues: ["28%", "4% 45m", "12%", "1%", "7%"],
    solAmount: 0,
    onSolButtonClick: () => alert("ZOOM Button Clicked!"),
  },
  {
    imageUrl: "/8.png",
    imageAlt: "MINT Token",
    address: "MINT...T1v5",
    showStatusIcon: false,
    name: "MINT",
    description: "Mint Factory",
    age: "15m",
    userCount: 67,
    flagCount: 2,
    trophyCount: 0,
    shieldStatus: "3/80",
    marketCap: "$190K",
    volume: "$28K",
    fee: 0.22,
    txCount: 345,
    badgeValues: ["8%", "1% 15m", "6%", "8%", "2%"],
    solAmount: 0,
    onSolButtonClick: () => alert("MINT Button Clicked!"),
  },
  {
    imageUrl: "/9.png",
    imageAlt: "FLUX Token",
    address: "FLUX...X6b9",
    showStatusIcon: true,
    name: "FLUX",
    description: "Flux Dynamics",
    age: "5m",
    userCount: 201,
    flagCount: 0,
    trophyCount: 1,
    shieldStatus: "12/45",
    marketCap: "$420K",
    volume: "$65K",
    fee: 0.12,
    txCount: 623,
    badgeValues: ["22%", "6% 5m", "10%", "2%", "5%"],
    solAmount: 0,
    onSolButtonClick: () => alert("FLUX Button Clicked!"),
  },
  {
    imageUrl: "/10.png",
    imageAlt: "WAVE Token",
    address: "WAVE...E4c7",
    showStatusIcon: false,
    name: "WAVE",
    description: "Wave Protocol",
    age: "20m",
    userCount: 78,
    flagCount: 1,
    trophyCount: 0,
    shieldStatus: "6/120",
    marketCap: "$310K",
    volume: "$40K",
    fee: 0.18,
    txCount: 456,
    badgeValues: ["15%", "3% 20m", "9%", "4%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("WAVE Button Clicked!"),
  },
  {
    imageUrl: "/11.png",
    imageAlt: "CORE Token",
    address: "CORE...E8w2",
    showStatusIcon: true,
    name: "CORE",
    description: "Core Systems",
    age: "35m",
    userCount: 156,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "18/70",
    marketCap: "$780K",
    volume: "$95K",
    fee: 0.09,
    txCount: 890,
    badgeValues: ["32%", "7% 35m", "14%", "3%", "9%"],
    solAmount: 0,
    onSolButtonClick: () => alert("CORE Button Clicked!"),
  },
  {
    imageUrl: "/12.png",
    imageAlt: "BEAM Token",
    address: "BEAM...M9t3",
    showStatusIcon: false,
    name: "BEAM",
    description: "Beam Network",
    age: "12m",
    userCount: 92,
    flagCount: 3,
    trophyCount: 0,
    shieldStatus: "4/90",
    marketCap: "$230K",
    volume: "$32K",
    fee: 0.25,
    txCount: 378,
    badgeValues: ["10%", "2% 12m", "7%", "12%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("BEAM Button Clicked!"),
  },
  {
    imageUrl: "/13.png",
    imageAlt: "SPARK Token",
    address: "SPRK...K5n1",
    showStatusIcon: true,
    name: "SPARK",
    description: "Spark Energy",
    age: "8m",
    userCount: 167,
    flagCount: 0,
    trophyCount: 1,
    shieldStatus: "9/55",
    marketCap: "$580K",
    volume: "$72K",
    fee: 0.07,
    txCount: 745,
    badgeValues: ["26%", "5% 8m", "11%", "2%", "6%"],
    solAmount: 0,
    onSolButtonClick: () => alert("SPARK Button Clicked!"),
  },
  {
    imageUrl: "/14.png",
    imageAlt: "GLOW Token",
    address: "GLOW...W7q4",
    showStatusIcon: false,
    name: "GLOW",
    description: "Glow Protocol",
    age: "25m",
    userCount: 123,
    flagCount: 2,
    trophyCount: 0,
    shieldStatus: "7/65",
    marketCap: "$380K",
    volume: "$48K",
    fee: 0.16,
    txCount: 567,
    badgeValues: ["18%", "4% 25m", "8%", "7%", "3%"],
    solAmount: 0,
    onSolButtonClick: () => alert("GLOW Button Clicked!"),
  },
  {
    imageUrl: "/15.png",
    imageAlt: "ECHO Token",
    address: "ECHO...O2s8",
    showStatusIcon: true,
    name: "ECHO",
    description: "Echo Systems",
    age: "18m",
    userCount: 89,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "11/85",
    marketCap: "$460K",
    volume: "$58K",
    fee: 0.11,
    txCount: 634,
    badgeValues: ["21%", "3% 18m", "9%", "1%", "4%"],
    solAmount: 0,
    onSolButtonClick: () => alert("ECHO Button Clicked!"),
  },
];

// Final Stretch (tokens approaching key milestones - 15 unique tokens)
export const finalStretchData: TokenCardProps[] = [
  {
    imageUrl: "/16.png",
    imageAlt: "FINAL Token",
    address: "FINL...A1b2",
    showStatusIcon: true,
    name: "FINAL",
    description: "Final Protocol",
    age: "2d",
    userCount: 1250,
    flagCount: 0,
    trophyCount: 8,
    shieldStatus: "45/50",
    marketCap: "$2.1M",
    volume: "$380K",
    fee: 0.04,
    txCount: 15400,
    badgeValues: ["92%", "18% 1d", "35%", "8%", "15%"],
    solAmount: 0,
    onSolButtonClick: () => alert("FINAL Button Clicked!"),
  },
  {
    imageUrl: "/17.png",
    imageAlt: "STRETCH Token",
    address: "STCH...C3d4",
    showStatusIcon: false,
    name: "STRETCH",
    description: "Stretch Finance",
    age: "1d",
    userCount: 890,
    flagCount: 1,
    trophyCount: 5,
    shieldStatus: "38/40",
    marketCap: "$1.8M",
    volume: "$290K",
    fee: 0.06,
    txCount: 12800,
    badgeValues: ["88%", "12% 6h", "28%", "6%", "12%"],
    solAmount: 0,
    onSolButtonClick: () => alert("STRETCH Button Clicked!"),
  },
  {
    imageUrl: "/18.png",
    imageAlt: "MEGA Token",
    address: "MEGA...E5f6",
    showStatusIcon: true,
    name: "MEGA",
    description: "Mega Systems",
    age: "3d",
    userCount: 2100,
    flagCount: 0,
    trophyCount: 12,
    shieldStatus: "85/90",
    marketCap: "$4.5M",
    volume: "$650K",
    fee: 0.03,
    txCount: 28900,
    badgeValues: ["95%", "22% 12h", "45%", "12%", "18%"],
    solAmount: 0,
    onSolButtonClick: () => alert("MEGA Button Clicked!"),
  },
  {
    imageUrl: "/19.png",
    imageAlt: "RUSH Token",
    address: "RUSH...H7g8",
    showStatusIcon: false,
    name: "RUSH",
    description: "Rush Network",
    age: "4h",
    userCount: 1560,
    flagCount: 2,
    trophyCount: 6,
    shieldStatus: "78/80",
    marketCap: "$1.2M",
    volume: "$210K",
    fee: 0.08,
    txCount: 9800,
    badgeValues: ["85%", "15% 2h", "32%", "9%", "14%"],
    solAmount: 0,
    onSolButtonClick: () => alert("RUSH Button Clicked!"),
  },
  {
    imageUrl: "/20.png",
    imageAlt: "PEAK Token",
    address: "PEAK...K9i0",
    showStatusIcon: true,
    name: "PEAK",
    description: "Peak Performance",
    age: "6h",
    userCount: 1890,
    flagCount: 0,
    trophyCount: 9,
    shieldStatus: "92/95",
    marketCap: "$3.2M",
    volume: "$480K",
    fee: 0.05,
    txCount: 19600,
    badgeValues: ["90%", "16% 4h", "38%", "10%", "16%"],
    solAmount: 0,
    onSolButtonClick: () => alert("PEAK Button Clicked!"),
  },
  {
    imageUrl: "/1.png",
    imageAlt: "BOOST Token",
    address: "BOST...T1j2",
    showStatusIcon: false,
    name: "BOOST",
    description: "Boost Protocol",
    age: "8h",
    userCount: 1340,
    flagCount: 1,
    trophyCount: 7,
    shieldStatus: "68/70",
    marketCap: "$1.9M",
    volume: "$340K",
    fee: 0.07,
    txCount: 14200,
    badgeValues: ["87%", "14% 3h", "30%", "7%", "13%"],
    solAmount: 0,
    onSolButtonClick: () => alert("BOOST Button Clicked!"),
  },
  {
    imageUrl: "/2.png",
    imageAlt: "TURBO Token",
    address: "TRBO...O3k4",
    showStatusIcon: true,
    name: "TURBO",
    description: "Turbo Engine",
    age: "12h",
    userCount: 2250,
    flagCount: 0,
    trophyCount: 11,
    shieldStatus: "195/200",
    marketCap: "$5.1M",
    volume: "$780K",
    fee: 0.02,
    txCount: 31400,
    badgeValues: ["96%", "25% 6h", "48%", "15%", "20%"],
    solAmount: 0,
    onSolButtonClick: () => alert("TURBO Button Clicked!"),
  },
  {
    imageUrl: "/3.png",
    imageAlt: "ZOOM Token",
    address: "ZOOM...M5l6",
    showStatusIcon: false,
    name: "ZOOM",
    description: "Zoom Finance",
    age: "18h",
    userCount: 1680,
    flagCount: 3,
    trophyCount: 4,
    shieldStatus: "58/60",
    marketCap: "$1.4M",
    volume: "$250K",
    fee: 0.09,
    txCount: 11800,
    badgeValues: ["82%", "11% 8h", "25%", "11%", "10%"],
    solAmount: 0,
    onSolButtonClick: () => alert("ZOOM Button Clicked!"),
  },
  {
    imageUrl: "/4.png",
    imageAlt: "APEX Token",
    address: "APEX...X7m8",
    showStatusIcon: true,
    name: "APEX",
    description: "Apex Trading",
    age: "1d",
    userCount: 1950,
    flagCount: 0,
    trophyCount: 8,
    shieldStatus: "88/90",
    marketCap: "$2.8M",
    volume: "$420K",
    fee: 0.04,
    txCount: 17900,
    badgeValues: ["89%", "17% 12h", "34%", "8%", "15%"],
    solAmount: 0,
    onSolButtonClick: () => alert("APEX Button Clicked!"),
  },
  {
    imageUrl: "/5.png",
    imageAlt: "EDGE Token",
    address: "EDGE...E9n0",
    showStatusIcon: false,
    name: "EDGE",
    description: "Edge Protocol",
    age: "2d",
    userCount: 1420,
    flagCount: 2,
    trophyCount: 6,
    shieldStatus: "72/75",
    marketCap: "$1.6M",
    volume: "$280K",
    fee: 0.06,
    txCount: 13500,
    badgeValues: ["84%", "13% 1d", "27%", "9%", "11%"],
    solAmount: 0,
    onSolButtonClick: () => alert("EDGE Button Clicked!"),
  },
  {
    imageUrl: "/6.png",
    imageAlt: "PRIME Token",
    address: "PRIM...M1p2",
    showStatusIcon: true,
    name: "PRIME",
    description: "Prime Network",
    age: "5d",
    userCount: 2800,
    flagCount: 0,
    trophyCount: 15,
    shieldStatus: "148/150",
    marketCap: "$6.2M",
    volume: "$950K",
    fee: 0.01,
    txCount: 38700,
    badgeValues: ["98%", "28% 1d", "52%", "18%", "22%"],
    solAmount: 0,
    onSolButtonClick: () => alert("PRIME Button Clicked!"),
  },
  {
    imageUrl: "/7.png",
    imageAlt: "ULTRA Token",
    address: "ULTR...R3q4",
    showStatusIcon: false,
    name: "ULTRA",
    description: "Ultra Protocol",
    age: "3d",
    userCount: 1780,
    flagCount: 1,
    trophyCount: 9,
    shieldStatus: "116/120",
    marketCap: "$2.4M",
    volume: "$380K",
    fee: 0.05,
    txCount: 16800,
    badgeValues: ["91%", "19% 18h", "36%", "11%", "16%"],
    solAmount: 0,
    onSolButtonClick: () => alert("ULTRA Button Clicked!"),
  },
  {
    imageUrl: "/8.png",
    imageAlt: "FLASH Token",
    address: "FLSH...H5r6",
    showStatusIcon: true,
    name: "FLASH",
    description: "Flash Systems",
    age: "10h",
    userCount: 2150,
    flagCount: 0,
    trophyCount: 7,
    shieldStatus: "82/85",
    marketCap: "$3.8M",
    volume: "$590K",
    fee: 0.03,
    txCount: 24100,
    badgeValues: ["93%", "21% 4h", "42%", "13%", "17%"],
    solAmount: 0,
    onSolButtonClick: () => alert("FLASH Button Clicked!"),
  },
  {
    imageUrl: "/9.png",
    imageAlt: "SPEED Token",
    address: "SPED...D7s8",
    showStatusIcon: false,
    name: "SPEED",
    description: "Speed Network",
    age: "14h",
    userCount: 1620,
    flagCount: 2,
    trophyCount: 5,
    shieldStatus: "64/65",
    marketCap: "$1.7M",
    volume: "$310K",
    fee: 0.07,
    txCount: 12900,
    badgeValues: ["86%", "12% 6h", "29%", "8%", "12%"],
    solAmount: 0,
    onSolButtonClick: () => alert("SPEED Button Clicked!"),
  },
  {
    imageUrl: "/10.png",
    imageAlt: "POWER Token",
    address: "POWR...R9t0",
    showStatusIcon: true,
    name: "POWER",
    description: "Power Protocol",
    age: "1d",
    userCount: 2400,
    flagCount: 0,
    trophyCount: 10,
    shieldStatus: "98/100",
    marketCap: "$4.1M",
    volume: "$620K",
    fee: 0.02,
    txCount: 27500,
    badgeValues: ["94%", "24% 8h", "46%", "14%", "19%"],
    solAmount: 0,
    onSolButtonClick: () => alert("POWER Button Clicked!"),
  },
];

// Migrated (fully migrated tokens - 15 unique tokens)
export const migratedTokensData: TokenCardProps[] = [
  {
    imageUrl: "/11.png",
    imageAlt: "LEGACY Token",
    address: "LGCY...Y1a2",
    showStatusIcon: true,
    name: "LEGACY",
    description: "Legacy Systems",
    age: "6mo",
    userCount: 5600,
    flagCount: 0,
    trophyCount: 25,
    shieldStatus: "200/200",
    marketCap: "$12.5M",
    volume: "$1.8M",
    fee: 0.01,
    txCount: 78900,
    badgeValues: ["100%", "stable", "60%", "25%", "30%"],
    solAmount: 0,
    onSolButtonClick: () => alert("LEGACY Button Clicked!"),
  },
  {
    imageUrl: "/12.png",
    imageAlt: "STABLE Token",
    address: "STBL...B3c4",
    showStatusIcon: false,
    name: "STABLE",
    description: "Stable Protocol",
    age: "1yr",
    userCount: 8900,
    flagCount: 0,
    trophyCount: 42,
    shieldStatus: "500/500",
    marketCap: "$25.8M",
    volume: "$3.2M",
    fee: 0.005,
    txCount: 156400,
    badgeValues: ["100%", "stable", "85%", "40%", "45%"],
    solAmount: 0,
    onSolButtonClick: () => alert("STABLE Button Clicked!"),
  },
  {
    imageUrl: "/13.png",
    imageAlt: "SOLID Token",
    address: "SLID...D5e6",
    showStatusIcon: true,
    name: "SOLID",
    description: "Solid Network",
    age: "8mo",
    userCount: 4200,
    flagCount: 0,
    trophyCount: 18,
    shieldStatus: "300/300",
    marketCap: "$8.9M",
    volume: "$1.2M",
    fee: 0.02,
    txCount: 52300,
    badgeValues: ["100%", "stable", "45%", "18%", "22%"],
    solAmount: 0,
    onSolButtonClick: () => alert("SOLID Button Clicked!"),
  },
  {
    imageUrl: "/14.png",
    imageAlt: "PROVEN Token",
    address: "PRVN...N7f8",
    showStatusIcon: false,
    name: "PROVEN",
    description: "Proven Protocol",
    age: "4mo",
    userCount: 3800,
    flagCount: 0,
    trophyCount: 15,
    shieldStatus: "250/250",
    marketCap: "$6.7M",
    volume: "$890K",
    fee: 0.03,
    txCount: 41200,
    badgeValues: ["100%", "stable", "38%", "15%", "18%"],
    solAmount: 0,
    onSolButtonClick: () => alert("PROVEN Button Clicked!"),
  },
  {
    imageUrl: "/15.png",
    imageAlt: "MATURE Token",
    address: "MTUR...R9g0",
    showStatusIcon: true,
    name: "MATURE",
    description: "Mature Systems",
    age: "2yr",
    userCount: 12500,
    flagCount: 0,
    trophyCount: 68,
    shieldStatus: "1000/1000",
    marketCap: "$45.2M",
    volume: "$6.8M",
    fee: 0.001,
    txCount: 289400,
    badgeValues: ["100%", "stable", "125%", "68%", "75%"],
    solAmount: 0,
    onSolButtonClick: () => alert("MATURE Button Clicked!"),
  },
  {
    imageUrl: "/16.png",
    imageAlt: "ROCK Token",
    address: "ROCK...K1h2",
    showStatusIcon: false,
    name: "ROCK",
    description: "Rock Solid",
    age: "10mo",
    userCount: 6800,
    flagCount: 0,
    trophyCount: 32,
    shieldStatus: "400/400",
    marketCap: "$18.4M",
    volume: "$2.4M",
    fee: 0.015,
    txCount: 98700,
    badgeValues: ["100%", "stable", "68%", "32%", "38%"],
    solAmount: 0,
    onSolButtonClick: () => alert("ROCK Button Clicked!"),
  },
  {
    imageUrl: "/17.png",
    imageAlt: "STRONG Token",
    address: "STRG...G3i4",
    showStatusIcon: true,
    name: "STRONG",
    description: "Strong Network",
    age: "7mo",
    userCount: 5400,
    flagCount: 0,
    trophyCount: 28,
    shieldStatus: "350/350",
    marketCap: "$14.2M",
    volume: "$1.9M",
    fee: 0.02,
    txCount: 72800,
    badgeValues: ["100%", "stable", "52%", "28%", "32%"],
    solAmount: 0,
    onSolButtonClick: () => alert("STRONG Button Clicked!"),
  },
  {
    imageUrl: "/18.png",
    imageAlt: "VAULT Token",
    address: "VULT...T5j6",
    showStatusIcon: false,
    name: "VAULT",
    description: "Vault Protocol",
    age: "1yr",
    userCount: 9200,
    flagCount: 0,
    trophyCount: 48,
    shieldStatus: "600/600",
    marketCap: "$32.1M",
    volume: "$4.2M",
    fee: 0.008,
    txCount: 187300,
    badgeValues: ["100%", "stable", "95%", "48%", "52%"],
    solAmount: 0,
    onSolButtonClick: () => alert("VAULT Button Clicked!"),
  },
  {
    imageUrl: "/19.png",
    imageAlt: "TITAN Token",
    address: "TITN...N7k8",
    showStatusIcon: true,
    name: "TITAN",
    description: "Titan Systems",
    age: "5mo",
    userCount: 4600,
    flagCount: 0,
    trophyCount: 22,
    shieldStatus: "280/280",
    marketCap: "$9.8M",
    volume: "$1.3M",
    fee: 0.025,
    txCount: 58900,
    badgeValues: ["100%", "stable", "42%", "22%", "25%"],
    solAmount: 0,
    onSolButtonClick: () => alert("TITAN Button Clicked!"),
  },
  {
    imageUrl: "/20.png",
    imageAlt: "FORTRESS Token",
    address: "FRTS...S9l0",
    showStatusIcon: false,
    name: "FORTRESS",
    description: "Fortress Network",
    age: "8mo",
    userCount: 7100,
    flagCount: 0,
    trophyCount: 38,
    shieldStatus: "450/450",
    marketCap: "$22.7M",
    volume: "$3.1M",
    fee: 0.01,
    txCount: 124600,
    badgeValues: ["100%", "stable", "78%", "38%", "42%"],
    solAmount: 0,
    onSolButtonClick: () => alert("FORTRESS Button Clicked!"),
  },
  {
    imageUrl: "/1.png",
    imageAlt: "ANCHOR Token",
    address: "ANCR...R1m2",
    showStatusIcon: true,
    name: "ANCHOR",
    description: "Anchor Protocol",
    age: "3mo",
    userCount: 3200,
    flagCount: 0,
    trophyCount: 12,
    shieldStatus: "180/180",
    marketCap: "$5.4M",
    volume: "$720K",
    fee: 0.04,
    txCount: 34800,
    badgeValues: ["100%", "stable", "28%", "12%", "15%"],
    solAmount: 0,
    onSolButtonClick: () => alert("ANCHOR Button Clicked!"),
  },
  {
    imageUrl: "/2.png",
    imageAlt: "SHIELD Token",
    address: "SHLD...D3n4",
    showStatusIcon: false,
    name: "SHIELD",
    description: "Shield Systems",
    age: "6mo",
    userCount: 5800,
    flagCount: 0,
    trophyCount: 35,
    shieldStatus: "320/320",
    marketCap: "$16.8M",
    volume: "$2.2M",
    fee: 0.015,
    txCount: 89400,
    badgeValues: ["100%", "stable", "62%", "35%", "38%"],
    solAmount: 0,
    onSolButtonClick: () => alert("SHIELD Button Clicked!"),
  },
  {
    imageUrl: "/3.png",
    imageAlt: "GUARDIAN Token",
    address: "GRDN...N5o6",
    showStatusIcon: true,
    name: "GUARDIAN",
    description: "Guardian Network",
    age: "9mo",
    userCount: 8400,
    flagCount: 0,
    trophyCount: 45,
    shieldStatus: "520/520",
    marketCap: "$28.9M",
    volume: "$3.8M",
    fee: 0.008,
    txCount: 156700,
    badgeValues: ["100%", "stable", "88%", "45%", "48%"],
    solAmount: 0,
    onSolButtonClick: () => alert("GUARDIAN Button Clicked!"),
  },
  {
    imageUrl: "/4.png",
    imageAlt: "BASTION Token",
    address: "BSTN...N7p8",
    showStatusIcon: false,
    name: "BASTION",
    description: "Bastion Protocol",
    age: "4mo",
    userCount: 4100,
    flagCount: 0,
    trophyCount: 19,
    shieldStatus: "220/220",
    marketCap: "$7.6M",
    volume: "$980K",
    fee: 0.03,
    txCount: 47300,
    badgeValues: ["100%", "stable", "35%", "19%", "22%"],
    solAmount: 0,
    onSolButtonClick: () => alert("BASTION Button Clicked!"),
  },
  {
    imageUrl: "/5.png",
    imageAlt: "ETERNAL Token",
    address: "ETNL...L9q0",
    showStatusIcon: true,
    name: "ETERNAL",
    description: "Eternal Systems",
    age: "1.5yr",
    userCount: 11200,
    flagCount: 0,
    trophyCount: 58,
    shieldStatus: "800/800",
    marketCap: "$38.4M",
    volume: "$5.2M",
    fee: 0.005,
    txCount: 234900,
    badgeValues: ["100%", "stable", "112%", "58%", "62%"],
    solAmount: 0,
    onSolButtonClick: () => alert("ETERNAL Button Clicked!"),
  },
];

// All tokens combined (for desktop view)
export const allTokensData: TokenCardProps[] = [
  {
    imageUrl: "/1.png",
    imageAlt: "DWA Token",
    address: "CLEQ...mNtR",
    showStatusIcon: true,
    name: "DWA",
    description: "Digital World Assets",
    age: "18m",
    userCount: 191,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "1/142",
    marketCap: "$535K",
    volume: "$35K",
    fee: 0.109,
    txCount: 796,
    badgeValues: ["13%", "0% 3d", "12%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("DWA Button Clicked!"),
  },
  {
    imageUrl: "/2.png",
    imageAlt: "Pixel Token",
    address: "PIXE...L8v9",
    showStatusIcon: false,
    name: "PIXEL",
    description: "Pixel Punks Coin",
    age: "2h",
    userCount: 2450,
    flagCount: 1,
    trophyCount: 5,
    shieldStatus: "12/50",
    marketCap: "$1.2M",
    volume: "$250K",
    fee: 0.05,
    txCount: 10240,
    badgeValues: ["88%", "2% 1d", "30%", "5%", "10%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Pixel Button Clicked!"),
  },
  {
    imageUrl: "/3.png",
    imageAlt: "Stardust Token",
    address: "STAR...DU5t",
    showStatusIcon: true,
    name: "STAR",
    description: "Stardust Ventures",
    age: "5d",
    userCount: 854,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "140/150",
    marketCap: "$812K",
    volume: "$98K",
    fee: 0.2,
    txCount: 2319,
    badgeValues: ["95%", "10% 8h", "5%", "0%", "2%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Stardust Button Clicked!"),
  },
  {
    imageUrl: "/4.png",
    imageAlt: "Volt Token",
    address: "VOLT...y7Gk",
    showStatusIcon: false,
    name: "VOLT",
    description: "Voltage Finance",
    age: "3m",
    userCount: 1205,
    flagCount: 2,
    trophyCount: 1,
    shieldStatus: "22/80",
    marketCap: "$2.5M",
    volume: "$450K",
    fee: 0.01,
    txCount: 15320,
    badgeValues: ["75%", "5% 2d", "20%", "3%", "8%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Volt Button Clicked!"),
  },
  {
    imageUrl: "/5.png",
    imageAlt: "Aqua Token",
    address: "AQUA...wA7r",
    showStatusIcon: true,
    name: "AQUA",
    description: "Aqua Protocol",
    age: "15m",
    userCount: 350,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "5/200",
    marketCap: "$250K",
    volume: "$15K",
    fee: 0.5,
    txCount: 540,
    badgeValues: ["20%", "0% 1d", "10%", "1%", "3%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Aqua Button Clicked!"),
  },
  {
    imageUrl: "/6.png",
    imageAlt: "Zephyr Token",
    address: "ZEPH...yR9t",
    showStatusIcon: false,
    name: "ZEPH",
    description: "Zephyr Network",
    age: "24h",
    userCount: 1890,
    flagCount: 0,
    trophyCount: 3,
    shieldStatus: "75/100",
    marketCap: "$950K",
    volume: "$120K",
    fee: 0.1,
    txCount: 8930,
    badgeValues: ["90%", "8% 12h", "15%", "2%", "5%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Zephyr Button Clicked!"),
  },
  {
    imageUrl: "/7.png",
    imageAlt: "Rift Token",
    address: "RIFT...vF3p",
    showStatusIcon: true,
    name: "RIFT",
    description: "Rift Valley Trading",
    age: "8d",
    userCount: 630,
    flagCount: 1,
    trophyCount: 1,
    shieldStatus: "30/50",
    marketCap: "$420K",
    volume: "$45K",
    fee: 0.25,
    txCount: 1780,
    badgeValues: ["60%", "1% 6h", "25%", "4%", "6%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Rift Button Clicked!"),
  },
  {
    imageUrl: "/8.png",
    imageAlt: "Orbit Token",
    address: "ORBT...iT8s",
    showStatusIcon: false,
    name: "ORBIT",
    description: "Orbital Systems",
    age: "1mo",
    userCount: 4500,
    flagCount: 5,
    trophyCount: 10,
    shieldStatus: "95/100",
    marketCap: "$5.8M",
    volume: "$1.1M",
    fee: 0.02,
    txCount: 52100,
    badgeValues: ["98%", "15% 1d", "40%", "10%", "12%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Orbit Button Clicked!"),
  },
  {
    imageUrl: "/9.png",
    imageAlt: "Fury Token",
    address: "FURY...yG4m",
    showStatusIcon: true,
    name: "FURY",
    description: "Fury Gaming",
    age: "5h",
    userCount: 980,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "50/120",
    marketCap: "$680K",
    volume: "$75K",
    fee: 0.3,
    txCount: 4100,
    badgeValues: ["45%", "3% 2h", "18%", "3%", "4%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Fury Button Clicked!"),
  },
  {
    imageUrl: "/10.png",
    imageAlt: "Jade Token",
    address: "JADE...eP6z",
    showStatusIcon: false,
    name: "JADE",
    description: "Jade Protocol",
    age: "12d",
    userCount: 210,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "10/300",
    marketCap: "$150K",
    volume: "$8K",
    fee: 0.8,
    txCount: 350,
    badgeValues: ["5%", "0% 5d", "5%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Jade Button Clicked!"),
  },
  {
    imageUrl: "/11.png",
    imageAlt: "Kronos Token",
    address: "KRON...oS1a",
    showStatusIcon: true,
    name: "KRON",
    description: "Kronos Timekeepers",
    age: "6mo",
    userCount: 880,
    flagCount: 1,
    trophyCount: 4,
    shieldStatus: "80/90",
    marketCap: "$3.1M",
    volume: "$320K",
    fee: 0.08,
    txCount: 18450,
    badgeValues: ["92%", "7% 3d", "35%", "6%", "9%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Kronos Button Clicked!"),
  },
  {
    imageUrl: "/12.png",
    imageAlt: "Neon Token",
    address: "NEON...nL9x",
    showStatusIcon: false,
    name: "NEON",
    description: "Neon District",
    age: "1h",
    userCount: 3100,
    flagCount: 3,
    trophyCount: 6,
    shieldStatus: "40/60",
    marketCap: "$1.8M",
    volume: "$300K",
    fee: 0.12,
    txCount: 12500,
    badgeValues: ["70%", "12% 30m", "28%", "8%", "11%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Neon Button Clicked!"),
  },
  {
    imageUrl: "/13.png",
    imageAlt: "Onyx Token",
    address: "ONYX...xT2c",
    showStatusIcon: true,
    name: "ONYX",
    description: "Onyx Network",
    age: "22d",
    userCount: 540,
    flagCount: 0,
    trophyCount: 1,
    shieldStatus: "110/120",
    marketCap: "$720K",
    volume: "$60K",
    fee: 0.18,
    txCount: 2900,
    badgeValues: ["85%", "4% 9h", "10%", "1%", "3%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Onyx Button Clicked!"),
  },
  {
    imageUrl: "/14.png",
    imageAlt: "Vexa Token",
    address: "VEXA...aV7q",
    showStatusIcon: true,
    name: "VEXA",
    description: "Vexa Trade Platform",
    age: "4mo",
    userCount: 1500,
    flagCount: 2,
    trophyCount: 3,
    shieldStatus: "65/100",
    marketCap: "$4.2M",
    volume: "$550K",
    fee: 0.06,
    txCount: 21000,
    badgeValues: ["80%", "6% 1d", "33%", "7%", "10%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Vexa Button Clicked!"),
  },
  {
    imageUrl: "/15.png",
    imageAlt: "Yara Token",
    address: "YARA...rY1b",
    showStatusIcon: false,
    name: "YARA",
    description: "Yara Growth Fund",
    age: "3h",
    userCount: 750,
    flagCount: 1,
    trophyCount: 0,
    shieldStatus: "15/150",
    marketCap: "$330K",
    volume: "$25K",
    fee: 0.45,
    txCount: 1100,
    badgeValues: ["25%", "1% 1h", "8%", "2%", "4%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Yara Button Clicked!"),
  },
];
