// lib/data.ts

import { TokenCardProps } from "./types";

// New tokens (recently launched - under 24h)
export const newTokensData: TokenCardProps[] = [
  {
    imageUrl: "/2.png",
    imageAlt: "Pixel Token",
    address: "PIXE...L8v9",
    showStatusIcon: false,
    name: "PIXEL",
    description: "Pixel Punks Coin",
    age: "2h",
    userCount: 2450,
    flagCount: 1,
    trophyCount: 5,
    shieldStatus: "12/50",
    marketCap: "$1.2M",
    volume: "$250K",
    fee: 0.05,
    txCount: 10240,
    badgeValues: ["88%", "2% 1d", "30%", "5%", "10%"],
    solAmount: 1.5,
    onSolButtonClick: () => alert("Pixel Button Clicked!"),
  },
  {
    imageUrl: "/9.png",
    imageAlt: "Fury Token",
    address: "FURY...yG4m",
    showStatusIcon: true,
    name: "FURY",
    description: "Fury Gaming",
    age: "5h",
    userCount: 980,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "50/120",
    marketCap: "$680K",
    volume: "$75K",
    fee: 0.3,
    txCount: 4100,
    badgeValues: ["45%", "3% 2h", "18%", "3%", "4%"],
    solAmount: 1.0,
    onSolButtonClick: () => alert("Fury Button Clicked!"),
  },
  {
    imageUrl: "/12.png",
    imageAlt: "Neon Token",
    address: "NEON...nL9x",
    showStatusIcon: false,
    name: "NEON",
    description: "Neon District",
    age: "1h",
    userCount: 3100,
    flagCount: 3,
    trophyCount: 6,
    shieldStatus: "40/60",
    marketCap: "$1.8M",
    volume: "$300K",
    fee: 0.12,
    txCount: 12500,
    badgeValues: ["70%", "12% 30m", "28%", "8%", "11%"],
    solAmount: 8.2,
    onSolButtonClick: () => alert("Neon Button Clicked!"),
  },
  {
    imageUrl: "/15.png",
    imageAlt: "Yara Token",
    address: "YARA...rY1b",
    showStatusIcon: false,
    name: "YARA",
    description: "Yara Growth Fund",
    age: "3h",
    userCount: 750,
    flagCount: 1,
    trophyCount: 0,
    shieldStatus: "15/150",
    marketCap: "$330K",
    volume: "$25K",
    fee: 0.45,
    txCount: 1100,
    badgeValues: ["25%", "1% 1h", "8%", "2%", "4%"],
    solAmount: 0.8,
    onSolButtonClick: () => alert("Yara Button Clicked!"),
  },
];

// Winners (highest performing tokens)
export const winnersTokensData: TokenCardProps[] = [
  {
    imageUrl: "/2.png",
    imageAlt: "Pixel Token",
    address: "PIXE...L8v9",
    showStatusIcon: false,
    name: "PIXEL",
    description: "Pixel Punks Coin",
    age: "2h",
    userCount: 2450,
    flagCount: 1,
    trophyCount: 5,
    shieldStatus: "12/50",
    marketCap: "$1.2M",
    volume: "$250K",
    fee: 0.05,
    txCount: 10240,
    badgeValues: ["88%", "2% 1d", "30%", "5%", "10%"],
    solAmount: 1.5,
    onSolButtonClick: () => alert("Pixel Button Clicked!"),
  },
  {
    imageUrl: "/8.png",
    imageAlt: "Orbit Token",
    address: "ORBT...iT8s",
    showStatusIcon: false,
    name: "ORBIT",
    description: "Orbital Systems",
    age: "1mo",
    userCount: 4500,
    flagCount: 5,
    trophyCount: 10,
    shieldStatus: "95/100",
    marketCap: "$5.8M",
    volume: "$1.1M",
    fee: 0.02,
    txCount: 52100,
    badgeValues: ["98%", "15% 1d", "40%", "10%", "12%"],
    solAmount: 25.0,
    onSolButtonClick: () => alert("Orbit Button Clicked!"),
  },
  {
    imageUrl: "/3.png",
    imageAlt: "Stardust Token",
    address: "STAR...DU5t",
    showStatusIcon: true,
    name: "STAR",
    description: "Stardust Ventures",
    age: "5d",
    userCount: 854,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "140/150",
    marketCap: "$812K",
    volume: "$98K",
    fee: 0.2,
    txCount: 2319,
    badgeValues: ["95%", "10% 8h", "5%", "0%", "2%"],
    solAmount: 10.2,
    onSolButtonClick: () => alert("Stardust Button Clicked!"),
  },
  {
    imageUrl: "/11.png",
    imageAlt: "Kronos Token",
    address: "KRON...oS1a",
    showStatusIcon: true,
    name: "KRON",
    description: "Kronos Timekeepers",
    age: "6mo",
    userCount: 880,
    flagCount: 1,
    trophyCount: 4,
    shieldStatus: "80/90",
    marketCap: "$3.1M",
    volume: "$320K",
    fee: 0.08,
    txCount: 18450,
    badgeValues: ["92%", "7% 3d", "35%", "6%", "9%"],
    solAmount: 12.5,
    onSolButtonClick: () => alert("Kronos Button Clicked!"),
  },
  {
    imageUrl: "/6.png",
    imageAlt: "Zephyr Token",
    address: "ZEPH...yR9t",
    showStatusIcon: false,
    name: "ZEPH",
    description: "Zephyr Network",
    age: "24h",
    userCount: 1890,
    flagCount: 0,
    trophyCount: 3,
    shieldStatus: "75/100",
    marketCap: "$950K",
    volume: "$120K",
    fee: 0.1,
    txCount: 8930,
    badgeValues: ["90%", "8% 12h", "15%", "2%", "5%"],
    solAmount: 2.1,
    onSolButtonClick: () => alert("Zephyr Button Clicked!"),
  },
];

// Losers (lowest performing tokens)
export const losersTokensData: TokenCardProps[] = [
  {
    imageUrl: "/1.png",
    imageAlt: "DWA Token",
    address: "CLEQ...mNtR",
    showStatusIcon: true,
    name: "DWA",
    description: "Digital World Assets",
    age: "18m",
    userCount: 191,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "1/142",
    marketCap: "$535K",
    volume: "$35K",
    fee: 0.109,
    txCount: 796,
    badgeValues: ["13%", "0% 3d", "12%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("DWA Button Clicked!"),
  },
  {
    imageUrl: "/5.png",
    imageAlt: "Aqua Token",
    address: "AQUA...wA7r",
    showStatusIcon: true,
    name: "AQUA",
    description: "Aqua Protocol",
    age: "15m",
    userCount: 350,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "5/200",
    marketCap: "$250K",
    volume: "$15K",
    fee: 0.5,
    txCount: 540,
    badgeValues: ["20%", "0% 1d", "10%", "1%", "3%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Aqua Button Clicked!"),
  },
  {
    imageUrl: "/10.png",
    imageAlt: "Jade Token",
    address: "JADE...eP6z",
    showStatusIcon: false,
    name: "JADE",
    description: "Jade Protocol",
    age: "12d",
    userCount: 210,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "10/300",
    marketCap: "$150K",
    volume: "$8K",
    fee: 0.8,
    txCount: 350,
    badgeValues: ["5%", "0% 5d", "5%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Jade Button Clicked!"),
  },
  {
    imageUrl: "/15.png",
    imageAlt: "Yara Token",
    address: "YARA...rY1b",
    showStatusIcon: false,
    name: "YARA",
    description: "Yara Growth Fund",
    age: "3h",
    userCount: 750,
    flagCount: 1,
    trophyCount: 0,
    shieldStatus: "15/150",
    marketCap: "$330K",
    volume: "$25K",
    fee: 0.45,
    txCount: 1100,
    badgeValues: ["25%", "1% 1h", "8%", "2%", "4%"],
    solAmount: 0.8,
    onSolButtonClick: () => alert("Yara Button Clicked!"),
  },
  {
    imageUrl: "/7.png",
    imageAlt: "Rift Token",
    address: "RIFT...vF3p",
    showStatusIcon: true,
    name: "RIFT",
    description: "Rift Valley Trading",
    age: "8d",
    userCount: 630,
    flagCount: 1,
    trophyCount: 1,
    shieldStatus: "30/50",
    marketCap: "$420K",
    volume: "$45K",
    fee: 0.25,
    txCount: 1780,
    badgeValues: ["60%", "1% 6h", "25%", "4%", "6%"],
    solAmount: 0.5,
    onSolButtonClick: () => alert("Rift Button Clicked!"),
  },
];

// All tokens combined (for desktop view)
export const allTokensData: TokenCardProps[] = [
  {
    imageUrl: "/1.png",
    imageAlt: "DWA Token",
    address: "CLEQ...mNtR",
    showStatusIcon: true,
    name: "DWA",
    description: "Digital World Assets",
    age: "18m",
    userCount: 191,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "1/142",
    marketCap: "$535K",
    volume: "$35K",
    fee: 0.109,
    txCount: 796,
    badgeValues: ["13%", "0% 3d", "12%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("DWA Button Clicked!"),
  },
  {
    imageUrl: "/2.png",
    imageAlt: "Pixel Token",
    address: "PIXE...L8v9",
    showStatusIcon: false,
    name: "PIXEL",
    description: "Pixel Punks Coin",
    age: "2h",
    userCount: 2450,
    flagCount: 1,
    trophyCount: 5,
    shieldStatus: "12/50",
    marketCap: "$1.2M",
    volume: "$250K",
    fee: 0.05,
    txCount: 10240,
    badgeValues: ["88%", "2% 1d", "30%", "5%", "10%"],
    solAmount: 1.5,
    onSolButtonClick: () => alert("Pixel Button Clicked!"),
  },
  {
    imageUrl: "/3.png",
    imageAlt: "Stardust Token",
    address: "STAR...DU5t",
    showStatusIcon: true,
    name: "STAR",
    description: "Stardust Ventures",
    age: "5d",
    userCount: 854,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "140/150",
    marketCap: "$812K",
    volume: "$98K",
    fee: 0.2,
    txCount: 2319,
    badgeValues: ["95%", "10% 8h", "5%", "0%", "2%"],
    solAmount: 10.2,
    onSolButtonClick: () => alert("Stardust Button Clicked!"),
  },
  {
    imageUrl: "/4.png",
    imageAlt: "Volt Token",
    address: "VOLT...y7Gk",
    showStatusIcon: false,
    name: "VOLT",
    description: "Voltage Finance",
    age: "3m",
    userCount: 1205,
    flagCount: 2,
    trophyCount: 1,
    shieldStatus: "22/80",
    marketCap: "$2.5M",
    volume: "$450K",
    fee: 0.01,
    txCount: 15320,
    badgeValues: ["75%", "5% 2d", "20%", "3%", "8%"],
    solAmount: 5.0,
    onSolButtonClick: () => alert("Volt Button Clicked!"),
  },
  {
    imageUrl: "/5.png",
    imageAlt: "Aqua Token",
    address: "AQUA...wA7r",
    showStatusIcon: true,
    name: "AQUA",
    description: "Aqua Protocol",
    age: "15m",
    userCount: 350,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "5/200",
    marketCap: "$250K",
    volume: "$15K",
    fee: 0.5,
    txCount: 540,
    badgeValues: ["20%", "0% 1d", "10%", "1%", "3%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Aqua Button Clicked!"),
  },
  {
    imageUrl: "/6.png",
    imageAlt: "Zephyr Token",
    address: "ZEPH...yR9t",
    showStatusIcon: false,
    name: "ZEPH",
    description: "Zephyr Network",
    age: "24h",
    userCount: 1890,
    flagCount: 0,
    trophyCount: 3,
    shieldStatus: "75/100",
    marketCap: "$950K",
    volume: "$120K",
    fee: 0.1,
    txCount: 8930,
    badgeValues: ["90%", "8% 12h", "15%", "2%", "5%"],
    solAmount: 2.1,
    onSolButtonClick: () => alert("Zephyr Button Clicked!"),
  },
  {
    imageUrl: "/7.png",
    imageAlt: "Rift Token",
    address: "RIFT...vF3p",
    showStatusIcon: true,
    name: "RIFT",
    description: "Rift Valley Trading",
    age: "8d",
    userCount: 630,
    flagCount: 1,
    trophyCount: 1,
    shieldStatus: "30/50",
    marketCap: "$420K",
    volume: "$45K",
    fee: 0.25,
    txCount: 1780,
    badgeValues: ["60%", "1% 6h", "25%", "4%", "6%"],
    solAmount: 0.5,
    onSolButtonClick: () => alert("Rift Button Clicked!"),
  },
  {
    imageUrl: "/8.png",
    imageAlt: "Orbit Token",
    address: "ORBT...iT8s",
    showStatusIcon: false,
    name: "ORBIT",
    description: "Orbital Systems",
    age: "1mo",
    userCount: 4500,
    flagCount: 5,
    trophyCount: 10,
    shieldStatus: "95/100",
    marketCap: "$5.8M",
    volume: "$1.1M",
    fee: 0.02,
    txCount: 52100,
    badgeValues: ["98%", "15% 1d", "40%", "10%", "12%"],
    solAmount: 25.0,
    onSolButtonClick: () => alert("Orbit Button Clicked!"),
  },
  {
    imageUrl: "/9.png",
    imageAlt: "Fury Token",
    address: "FURY...yG4m",
    showStatusIcon: true,
    name: "FURY",
    description: "Fury Gaming",
    age: "5h",
    userCount: 980,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "50/120",
    marketCap: "$680K",
    volume: "$75K",
    fee: 0.3,
    txCount: 4100,
    badgeValues: ["45%", "3% 2h", "18%", "3%", "4%"],
    solAmount: 1.0,
    onSolButtonClick: () => alert("Fury Button Clicked!"),
  },
  {
    imageUrl: "/10.png",
    imageAlt: "Jade Token",
    address: "JADE...eP6z",
    showStatusIcon: false,
    name: "JADE",
    description: "Jade Protocol",
    age: "12d",
    userCount: 210,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "10/300",
    marketCap: "$150K",
    volume: "$8K",
    fee: 0.8,
    txCount: 350,
    badgeValues: ["5%", "0% 5d", "5%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("Jade Button Clicked!"),
  },
  {
    imageUrl: "/11.png",
    imageAlt: "Kronos Token",
    address: "KRON...oS1a",
    showStatusIcon: true,
    name: "KRON",
    description: "Kronos Timekeepers",
    age: "6mo",
    userCount: 880,
    flagCount: 1,
    trophyCount: 4,
    shieldStatus: "80/90",
    marketCap: "$3.1M",
    volume: "$320K",
    fee: 0.08,
    txCount: 18450,
    badgeValues: ["92%", "7% 3d", "35%", "6%", "9%"],
    solAmount: 12.5,
    onSolButtonClick: () => alert("Kronos Button Clicked!"),
  },
  {
    imageUrl: "/12.png",
    imageAlt: "Neon Token",
    address: "NEON...nL9x",
    showStatusIcon: false,
    name: "NEON",
    description: "Neon District",
    age: "1h",
    userCount: 3100,
    flagCount: 3,
    trophyCount: 6,
    shieldStatus: "40/60",
    marketCap: "$1.8M",
    volume: "$300K",
    fee: 0.12,
    txCount: 12500,
    badgeValues: ["70%", "12% 30m", "28%", "8%", "11%"],
    solAmount: 8.2,
    onSolButtonClick: () => alert("Neon Button Clicked!"),
  },
  {
    imageUrl: "/13.png",
    imageAlt: "Onyx Token",
    address: "ONYX...xT2c",
    showStatusIcon: true,
    name: "ONYX",
    description: "Onyx Network",
    age: "22d",
    userCount: 540,
    flagCount: 0,
    trophyCount: 1,
    shieldStatus: "110/120",
    marketCap: "$720K",
    volume: "$60K",
    fee: 0.18,
    txCount: 2900,
    badgeValues: ["85%", "4% 9h", "10%", "1%", "3%"],
    solAmount: 3.3,
    onSolButtonClick: () => alert("Onyx Button Clicked!"),
  },
  {
    imageUrl: "/14.png",
    imageAlt: "Vexa Token",
    address: "VEXA...aV7q",
    showStatusIcon: true,
    name: "VEXA",
    description: "Vexa Trade Platform",
    age: "4mo",
    userCount: 1500,
    flagCount: 2,
    trophyCount: 3,
    shieldStatus: "65/100",
    marketCap: "$4.2M",
    volume: "$550K",
    fee: 0.06,
    txCount: 21000,
    badgeValues: ["80%", "6% 1d", "33%", "7%", "10%"],
    solAmount: 18.0,
    onSolButtonClick: () => alert("Vexa Button Clicked!"),
  },
  {
    imageUrl: "/15.png",
    imageAlt: "Yara Token",
    address: "YARA...rY1b",
    showStatusIcon: false,
    name: "YARA",
    description: "Yara Growth Fund",
    age: "3h",
    userCount: 750,
    flagCount: 1,
    trophyCount: 0,
    shieldStatus: "15/150",
    marketCap: "$330K",
    volume: "$25K",
    fee: 0.45,
    txCount: 1100,
    badgeValues: ["25%", "1% 1h", "8%", "2%", "4%"],
    solAmount: 0.8,
    onSolButtonClick: () => alert("Yara Button Clicked!"),
  },
];
