// lib/data.ts

import { TokenCardProps } from "./types";

export const allTokensData: TokenCardProps[] = [
  {
    imageUrl: "/1.png",
    imageAlt: "DWA Token",
    address: "CLEQ...mNtR",
    showStatusIcon: true,
    name: "DWA",
    description: "Digital World Assets",
    age: "18m",
    userCount: 191,
    flagCount: 0,
    trophyCount: 0,
    shieldStatus: "1/142",
    marketCap: "$535K",
    volume: "$35K",
    fee: 0.109,
    txCount: 796,
    badgeValues: ["13%", "0% 3d", "12%", "0%", "1%"],
    solAmount: 0,
    onSolButtonClick: () => alert("DWA Button Clicked!"),
  },
  {
    imageUrl: "/2.png",
    imageAlt: "Pixel Token",
    address: "PIXE...L8v9",
    showStatusIcon: false,
    name: "PIXEL",
    description: "Pixel Punks Coin",
    age: "2h",
    userCount: 2450,
    flagCount: 1,
    trophyCount: 5,
    shieldStatus: "12/50",
    marketCap: "$1.2M",
    volume: "$250K",
    fee: 0.05,
    txCount: 10240,
    badgeValues: ["88%", "2% 1d", "30%", "5%", "10%"],
    solAmount: 1.5,
    onSolButtonClick: () => alert("Pixel Button Clicked!"),
  },
  {
    imageUrl: "/3.png",
    imageAlt: "Stardust Token",
    address: "STAR...DU5t",
    showStatusIcon: true,
    name: "STAR",
    description: "Stardust Ventures",
    age: "5d",
    userCount: 854,
    flagCount: 0,
    trophyCount: 2,
    shieldStatus: "140/150",
    marketCap: "$812K",
    volume: "$98K",
    fee: 0.2,
    txCount: 2319,
    badgeValues: ["95%", "10% 8h", "5%", "0%", "2%"],
    solAmount: 10.2,
    onSolButtonClick: () => alert("Stardust Button Clicked!"),
  },
];
